//HintName: LocalizationProviderAttribute.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the TypesafeLocalization source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TypesafeLocalization;

[System.AttributeUsage(System.AttributeTargets.Assembly)]
public sealed class LocalizationProviderAttribute : System.Attribute
{
  public Locale? BaseLocale { get; set; }
}