//HintName: TranslationNotFoundException.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the TypesafeLocalization source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TypesafeLocalization;

public sealed class TranslationNotFoundException : Exception
{
    public string Key { get; }
    public Locale Locale { get; }

    public TranslationNotFoundException(string key, Locale locale)
        : base($"Translation for key {key} in locale {locale} not found")
    {
        Key = key;
        Locale = locale;
    }
}