//HintName: LocalizerFactory.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the TypesafeLocalization source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TypesafeLocalization;

public sealed class LocalizerFactory : ILocalizerFactory
{
    public ILocalizer CreateLocalizer(Locale locale)
    {
        return new Localizer(locale);
    }
}