//HintName: Localizer.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the TypesafeLocalization source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TypesafeLocalization;

public sealed class Localizer : ILocalizer
{
    private readonly Locale _locale;

    public Localizer(Locale locale)
    {
        _locale = locale;
    }

    public string Key1()
    {
        return _locale switch
        {
            Locale.enUS => "Value 1",
            Locale.ruRU => "Значение 1",
            _ => throw new ArgumentOutOfRangeException()
        };
    }

    public string Key2()
    {
        return _locale switch
        {
            Locale.enUS => "Value 2",
            Locale.ruRU => "Значение 2",
            _ => throw new ArgumentOutOfRangeException()
        };
    }

    public string Key3()
    {
        return _locale switch
        {
            Locale.enUS => "Value 3",
            Locale.ruRU => "Значение 3",
            _ => throw new ArgumentOutOfRangeException()
        };
    }

}
