using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace TypesafeLocalization;

public static class SourceGenerationHelper
{
    private const string Namespace = "TypesafeLocalization";

    private static SyntaxTrivia FileHeader()
    {
        const string text = $"""
                             //------------------------------------------------------------------------------
                             // <auto-generated>
                             //     This code was generated by the {Namespace} source generator
                             //
                             //     Changes to this file may cause incorrect behavior and will be lost if
                             //     the code is regenerated.
                             // </auto-generated>
                             //------------------------------------------------------------------------------
                             """;

        return SyntaxFactory.Comment(text);
    }

    public static SourceText LocaleEnum(IEnumerable<string> locales)
    {
        var syntaxes = locales
            .Select(NormalizeLocaleName)
            .Select(SyntaxFactory.EnumMemberDeclaration);

        var syntaxesList = new SeparatedSyntaxList<EnumMemberDeclarationSyntax>();
        syntaxesList = syntaxesList.AddRange(syntaxes);

        var enumDeclaration = SyntaxFactory.EnumDeclaration("Locale")
            .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword))
            .WithMembers(syntaxesList);

        var text = SyntaxFactory.FileScopedNamespaceDeclaration(SyntaxFactory.ParseName(Namespace))
            .WithLeadingTrivia(FileHeader())
            .AddMembers(enumDeclaration)
            .NormalizeWhitespace()
            .ToFullString();

        return SourceText.From(text, Encoding.UTF8);

        static string NormalizeLocaleName(string locale)
        {
            return locale
                .Replace("-", "")
                .Replace("_", "");
        }
    }

    public static SourceText LocalizationProviderAttribute()
    {
        var text = $$"""
                     {{FileHeader()}}
                     namespace {{Namespace}};

                     [System.AttributeUsage(System.AttributeTargets.Assembly)]
                     public sealed class LocalizationProviderAttribute : System.Attribute
                     {
                       public Locale? BaseLocale { get; set; }
                     }
                     """;

        return SourceText.From(text, Encoding.UTF8);
    }

    public static SourceText Localizer(IEnumerable<string> keys)
    {
        var interfaceDeclaration = SyntaxFactory.InterfaceDeclaration("ILocalizer")
            .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword))
            .AddMembers(keys.Select(LocalizationMethod).ToArray());

        var fullString = SyntaxFactory.FileScopedNamespaceDeclaration(SyntaxFactory.ParseName(Namespace))
            .WithLeadingTrivia(FileHeader())
            .AddMembers(interfaceDeclaration)
            .NormalizeWhitespace()
            .ToFullString();

        return SourceText.From(fullString, Encoding.UTF8);

        static MemberDeclarationSyntax LocalizationMethod(string key)
        {
            return SyntaxFactory.ParseMemberDeclaration($"string {key}();")!;
        }
    }
}
